"""
Django settings for SmartBazaar project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent     # "BASE_DIR" is the project-level directory i.e. "C:\Users\aravi\DjangoProjects\project_spider\SmartBazaar"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e&ah_^2dzn663e&3-#@af$)dgppd1+zjjt+oejs=i!(%=p_h+i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'category',                               # All the apps that we create (using the command "python manage.py startapp <app_name>") should be registered here in "INSTALLED_APPS"
    'accounts',
    'store',
    'carts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SmartBazaar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],         # This specify the directory which contains the template(i.e. home.html and other html files) which you want to render
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'category.context_processors.menu_links',                      # So by adding this here, we will be able to use this menu links in any templates we want. So that's the reason we use this context processors.
                'carts.context_processors.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartBazaar.wsgi.application'
AUTH_USER_MODEL = 'accounts.Account'                # telling the settings.py file that we are going to use custom user model.


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "sb_postgres",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR /"static"     # When we run the command (python manage.py collectstatic) all the static files are collected and stored in the directory specified by "STATIC_ROOT"
STATICFILES_DIRS = [                 # List of folders where django will look for static files when we run the command -> python manage.py runserver
    "SmartBazaar/static"
]

# media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /"media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# The below 3-4 line of code is the message-framework in django which will be used to show messages/alert
# dialogue box in UI
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: "danger",

}


# SMTP configuration ----- to send verification-mail for users
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'             The smtp configuration works without this line.
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587                                            # 587 is for gmail. for other mail system like yahoo etc the port will be different
EMAIL_HOST_USER = 'nairproject100@gmail.com'                # The gmail account from which you need to send the verification mail
EMAIL_HOST_PASSWORD = 'rmgf ufoh bofw shop'                 # The App Password of the above gmail account which you had to create in the gmail account
EMAIL_USE_TLS = True
